service:
  name: core-kafka-sender-util
  kafka:
    server: ${DEFAULT_KAFKA_SERVER}

# Логирование
logging:
  level:
    org:
      springframework: info
      springframework.orm: info
      springframework.web: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
